CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  account_id UUID,
  role VARCHAR(32) NOT NULL DEFAULT 'ADMIN',
  isBlocked BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(32) NOT NULL DEFAULT 'ADMIN';
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email ON users (LOWER(email));
