server:
  port: ${SENDER_PORT:8771}

springdoc:
  paths-to-match: /api/**
  swagger-ui:
    enabled: false

spring:
  application:
    name: email_sender
  output:
    ansi:
      enabled: ALWAYS
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
          ssl:
            trust: ${MAIL_HOST:smtp.gmail.com}
    test-connection: ${MAIL_TEST_CONNECTION:false}

logging:
  level:
    org.springframework.mail: INFO
  pattern:
    console: '%clr(%d{HH:mm:ss}){faint} %clr(%-5level) %clr([%logger{0}]){cyan} %clr(:){faint} %m%n'
